<? if( function_exists('acf_add_local_field_group') ):

/* Temoignages */
acf_add_local_field_group(array(
	'key' => 'group_5ba67078385a0',
	'title' => 'Citation',
	'fields' => array(
		array(
			'key' => 'field_5ba6719668b5f',
			'label' => '',
			'name' => 'quote',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonials',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

/* Coordonnées */
acf_add_local_field_group(array(
	'key' => 'group_5b925c016f2c0',
	'title' => 'Coordonées',
	'fields' => array(
		array(
			'key' => 'field_5b925c22860f8',
			'label' => 'Adresse',
			'name' => 'adress',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b925c39860f9',
			'label' => 'Email de contact',
			'name' => 'contact_mail',
			'type' => 'email',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_5b925c49860fa',
			'label' => 'Numéro de téléphone',
			'name' => 'pƒhone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b928b701bd43',
			'label' => 'Horaires',
			'name' => 'hours',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5b925d042c0a7',
			'label' => 'Réseaux sociaux',
			'name' => 'rs',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_5b925d192c0a8',
					'label' => 'Twitter',
					'name' => 'twitter',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b925d232c0a9',
					'label' => 'Facebook',
					'name' => 'facebook',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b925d2d2c0aa',
					'label' => 'Linkedin',
					'name' => 'linkedin',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b952b32cc454',
					'label' => 'Instagram',
					'name' => 'instagram',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5b952b4fcc455',
					'label' => 'Youtube',
					'name' => 'youtube',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

/* Informations membre de l'équipe */
acf_add_local_field_group(array(
	'key' => 'group_5ba61a37bbb9d',
	'title' => 'Informations',
	'fields' => array(
		array(
			'key' => 'field_5ba61a9963d92',
			'label' => 'Poste',
			'name' => 'job',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5ba61b7cec587',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'textarea',
			'instructions' => 'Courte description limitée à 160 charactères',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '160',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_5ba61aac63d93',
			'label' => 'Liens',
			'name' => 'links',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5ba61ac463d94',
					'label' => 'Site',
					'name' => 'website',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ba61acc63d95',
					'label' => 'Facebook',
					'name' => 'facebook',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ba61ade63d96',
					'label' => 'Twitter',
					'name' => 'twitter',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ba61ae663d97',
					'label' => 'Instagram',
					'name' => 'instagram',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ba61aef63d98',
					'label' => 'Google+',
					'name' => 'google',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5ba61afb63d99',
					'label' => 'Linkedin',
					'name' => 'linkedin',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'team',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

/* Sections */
acf_add_local_field_group(array(
	'key' => 'group_5b9bafa10a548',
	'title' => 'Sections',
	'fields' => array(
		array(
			'key' => 'field_5b9bafde734b5',
			'label' => 'Sections',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				/* Header */
				'5b9bb1c928aca' => array(
					'key' => '5b9bb1c928aca',
					'name' => 'header',
					'label' => 'Header',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9bb3d9734c1',
							'label' => 'Call to action 1',
							'name' => 'call_to_action_1',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5b9bb3f2734c2',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b9bb404734c3',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b9bb4a4734c4',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c3',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5b9bb4c7734c5',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c3',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),
						array(
							'key' => 'field_5b9bb3d9734c0',
							'label' => 'Call to action 2',
							'name' => 'call_to_action_2',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5b9bb3f2734c1',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b9bb404734c2',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b9bb4a4734c3',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c2',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5b9bb4c7734c4',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c2',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				/* TEXT */
				'5b9bb1c928ace' => array(
					'key' => '5b9bb1c928ace',
					'name' => 'text',
					'label' => 'Texte',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9bb1e1734b7',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'title',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b9bb20c734b8',
							'label' => 'Texte',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'basic',
							'media_upload' => 1,
							'delay' => 0,
                        ),
					),
					'min' => '',
					'max' => '',
				),
				/* TEXT + IMAGE */
				'layout_5b9bb2b0734ba' => array(
					'key' => 'layout_5b9bb2b0734ba',
					'name' => 'text_image',
					'label' => 'Texte et Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9bb2bc734bb',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b9bb2cd734bc',
							'label' => 'Texte',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5b9bb2e2734bd',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'img',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'medium',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5b9bb3d9734c2',
							'label' => 'Bouton',
							'name' => 'button',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5b9bb3f2734c3',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b9bb404734c4',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b9bb4a4734c5',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c4',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5b9bb4c7734c6',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c4',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				/* LINK */
				'layout_5b9bb37d734bf' => array(
					'key' => 'layout_5b9bb37d734bf',
					'name' => 'link',
					'label' => 'Lien',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b9bb37d734c0',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'section-title',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b9bb37d734c1',
							'label' => 'Texte',
							'name' => 'text',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5b9bb3d9734c3',
							'label' => 'Bouton',
							'name' => 'button',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_5b9bb3f2734c4',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b9bb404734c5',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b9bb4a4734c6',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c5',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5b9bb4c7734c7',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b9bb404734c5',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),
						array(
							'key' => 'field_5b9bb37d564c3',
							'label' => 'Fond',
							'name' => 'fond',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Blanc' => 'Blanc',
								'Gris' => 'Gris',
								'Couleur' => 'Couleur',
								'Image' => 'Image',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'Blanc',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5ba612cd36489',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b9bb37d564c3',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				/* SERVICES */
				'layout_5ba4acdb8648b' => array(
					'key' => 'layout_5ba4acdb8648b',
					'name' => 'services',
					'label' => 'Services',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68c24d1ddd',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba4ad318648f',
							'label' => 'Service',
							'name' => 'service',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5ba4ae5d86490',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ba4ae5d86480',
									'label' => 'Slogan',
									'name' => 'slogan_service',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ba4ae6586491',
									'label' => 'Texte',
									'name' => 'text',
									'type' => 'wysiwyg',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'rows' => '',
									'new_lines' => '',
								),
								array(
									'key' => 'field_5ba4ae7986492',
									'label' => 'Icon',
									'name' => 'icon',
									'type' => 'image',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
								),
							),
						),
						array(
							'key' => 'field_4b9bb3d9734c3',
							'label' => 'Bouton',
							'name' => 'button',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'sub_fields' => array(
								array(
									'key' => 'field_4b9bb3f2734c4',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_4b9bb404734c5',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 1,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_4b9bb4a4734c6',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_4b9bb404734c5',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_4b9bb4c7734c7',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_4b9bb404734c5',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),
					),
					'min' => '',
					'max' => '',
				),
				/* TEAM */
				'layout_5ba4af1886493' => array(
					'key' => 'layout_5ba4af1886493',
					'name' => 'team',
					'label' => 'Équipe',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba61d2b70c62',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Le titre affiché dans la section',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba61d4d70c63',
							'label' => 'Fond',
							'name' => 'fond',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Blanc' => 'Blanc',
								'Gris' => 'Gris',
								'Couleur' => 'Couleur',
								'Image' => 'Image',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'Blanc',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5ba61dba70c65',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ba61d4d70c63',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '1',
				),
				/* PORTFOLIO */
				'layout_5ba630200ea4a' => array(
					'key' => 'layout_5ba630200ea4a',
					'name' => 'portfolio',
					'label' => 'Portfolio',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba630200ea4b',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Le titre affiché dans la section',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),

						array(
							'key' => 'field_5ba630200ea12',
							'label' => 'Slogan',
							'name' => 'slogan_title',
							'type' => 'text',
							'instructions' => 'Slogan du portfolio',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '1',
				),
				/* TESTIMONIALS */
				'layout_5ba630a0a7bfc' => array(
					'key' => 'layout_5ba630a0a7bfc',
					'name' => 'testimonials',
					'label' => 'Témoignages',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba630a0a7bfd',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => 'Le titre affiché dans la section',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba630a0a7bfe',
							'label' => 'Fond',
							'name' => 'fond',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Blanc' => 'Blanc',
								'Gris' => 'Gris',
								'Couleur' => 'Couleur',
								'Image' => 'Image',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'Blanc',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_5ba630a0a7c00',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5ba630a0a7bfe',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '1',
				),
				/* PRICE */
				'layout_5ba502470c6c0' => array(
					'key' => 'layout_5ba502470c6c0',
					'name' => 'price',
					'label' => 'Prix',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68c35d1dde',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b3eb37d734c2',
							'label' => 'Fond',
							'name' => 'fond',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'Blanc' => 'Blanc',
								'Gris' => 'Gris',
								'Couleur' => 'Couleur',
								'Image' => 'Image',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => 'Gris',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5ba625cd54789',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_5b9bb37d734c3',
										'operator' => '==',
										'value' => 'Image',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5ba502550c6c1',
							'label' => 'Colonne',
							'name' => 'colonne',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'row',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5ba502770c6c2',
									'label' => 'Title',
									'name' => 'title',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ba502810c6c3',
									'label' => 'Prix',
									'name' => 'prix',
									'type' => 'number',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'min' => '',
									'max' => '',
									'step' => '',
								),
								array(
									'key' => 'field_5ba502c60c6c4',
									'label' => 'Devise',
									'name' => 'devise',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'€' => '€',
										'$' => '$',
										'£' => '£',
										'¥' => '¥',
									),
									'default_value' => array(
										0 => '€',
									),
									'allow_null' => 0,
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ba503630c6c5',
									'label' => 'Services',
									'name' => 'services',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 0,
									'max' => 0,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'field_5ba5037b0c6c6',
											'label' => 'Texte',
											'name' => 'text',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
								),
								array(
									'key' => 'field_5ba5040c0c6c7',
									'label' => 'Bouton',
									'name' => 'button',
									'type' => 'group',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'layout' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5ba504470c6c8',
											'label' => 'Label',
											'name' => 'label',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5ba504670c6c9',
											'label' => 'Lien',
											'name' => 'link',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'Interne' => 'Interne',
												'Externe' => 'Externe',
											),
											'allow_null' => 0,
											'other_choice' => 0,
											'default_value' => 'Externe',
											'layout' => 'vertical',
											'return_format' => 'value',
											'save_other_choice' => 0,
										),
										array(
											'key' => 'field_5ba6129e0c6ca',
											'label' => '',
											'name' => 'url',
											'type' => 'url',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ba504670c6c9',
														'operator' => '==',
														'value' => 'Externe',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
										),
										array(
											'key' => 'field_5ba613070c6cb',
											'label' => '',
											'name' => 'int_url',
											'type' => 'page_link',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => array(
												array(
													array(
														'field' => 'field_5ba504670c6c9',
														'operator' => '==',
														'value' => 'Interne',
													),
												),
											),
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'post_type' => '',
											'taxonomy' => '',
											'allow_null' => 0,
											'allow_archives' => 1,
											'multiple' => 0,
										),
									),
								),
							),
						),

					),
					'min' => '',
					'max' => '4',
				),
				/* LOGOS */
				'layout_5ba6725ceb0fa' => array(
					'key' => 'layout_5ba6725ceb0fa',
					'name' => 'logos',
					'label' => 'Logos',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68b9426093',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba68a858e163',
							'label' => '',
							'name' => 'logo_list',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				/* CAROUSEL */
				'layout_5ba672c4eb0fd' => array(
					'key' => 'layout_5ba672c4eb0fd',
					'name' => 'carousel',
					'label' => 'Carousel',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68c56d1ddf',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba672ceeb0fe',
							'label' => 'Images',
							'name' => 'images',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'insert' => 'append',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				/* GALLERY */
				'layout_5ba672f6eb0ff' => array(
					'key' => 'layout_5ba672f6eb0ff',
					'name' => 'gallery',
					'label' => 'Gallerie',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68c64d1de0',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba672f6eb100',
							'label' => 'Images',
							'name' => 'images',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'min' => '',
							'max' => '',
							'insert' => 'append',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				/* CONTACT */
				'layout_5ba67318eb101' => array(
					'key' => 'layout_5ba67318eb101',
					'name' => 'contact',
					'label' => 'Contact',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5ba68c6fd1de1',
							'label' => 'Titre',
							'name' => 'title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba6741f00102',
							'label' => 'Contact Form',
							'name' => 'contact_form',
							'type' => 'cf7',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
						),
						array(
							'key' => 'field_5b9bb37d734c2',
							'label' => 'Texte',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'Oui',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5ba5040c0c6c6',
							'label' => 'Bouton',
							'name' => 'button',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_5ba504470c6c7',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5ba504670c6c8',
									'label' => 'Lien',
									'name' => 'link',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'Interne' => 'Interne',
										'Externe' => 'Externe',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'Externe',
									'layout' => 'vertical',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5ba6129e0c6cb',
									'label' => '',
									'name' => 'url',
									'type' => 'url',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5ba504670c6c0',
												'operator' => '==',
												'value' => 'Externe',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
								),
								array(
									'key' => 'field_5ba613070c6cc',
									'label' => '',
									'name' => 'int_url',
									'type' => 'page_link',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5ba504670c6c0',
												'operator' => '==',
												'value' => 'Interne',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'post_type' => '',
									'taxonomy' => '',
									'allow_null' => 0,
									'allow_archives' => 1,
									'multiple' => 0,
								),
							),
						),

					),
					'min' => '',
					'max' => '',
				),
				/* STATS */
				'layout_5b86744c3c170' => array(
					'key' => 'layout_5b86744c3c170',
					'name' => 'stats',
					'label' => 'Statistiques',
					'display' => 'block',
					'sub_fields' => array(
					 array(
						 'key' => 'field_5b8c1b33b5cf8',
						 'label' => 'Titre',
						 'name' => 'title',
						 'type' => 'text',
						 'instructions' => '',
						 'required' => 0,
						 'conditional_logic' => 0,
						 'wrapper' => array(
							 'width' => '',
							 'class' => '',
							 'id' => '',
						 ),
						 'default_value' => '',
						 'placeholder' => '',
						 'prepend' => '',
						 'append' => '',
						 'maxlength' => '',
					 ),
						array(
							'key' => 'field_5b86745a3c171',
							'label' => 'Jauges',
							'name' => 'radial_chart',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => 'Ajouter une jauge',
							'sub_fields' => array(
								array(
									'key' => 'field_5b8674b93c172',
									'label' => 'Opérateur',
									'name' => 'operateur',
									'type' => 'select',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'' => 'Aucun',
										'+' => '+',
										'-' => '-',
										'%' => '%',
									),
									'default_value' => array(
										0 => 'Aucun',
									),
									'multiple' => 0,
									'ui' => 0,
									'return_format' => 'value',
									'ajax' => 0,
									'placeholder' => '',
								),
								array(
									'key' => 'field_5b86750f3c173',
									'label' => 'Pourcentage',
									'name' => 'percentage',
									'type' => 'number',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '%',
									'min' => 0,
									'max' => '',
									'step' => '',
								),
								array(
									'key' => 'field_5b86b24d1b9fe',
									'label' => 'Label',
									'name' => 'label',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
					),
					'min' => '',
					'max' => '1',
				),
							/* FAQ */
							'layout_5b86744c3c176' => array(
								'key' => 'layout_5b86744c3c176',
								'name' => 'faq',
								'label' => 'FAQ',
								'display' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5b9bb37d214c0',
										'label' => 'Titre',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => 'section-title',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5bd7693a51484',
										'label' => 'FAQ',
										'name' => 'faq',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => '',
										'sub_fields' => array(
											array(
												'key' => 'field_5bd7694d51485',
												'label' => 'Question',
												'name' => 'question',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5bd7695651486',
												'label' => 'Réponse',
												'name' => 'answer',
												'type' => 'textarea',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'maxlength' => '',
												'rows' => '',
												'new_lines' => '',
											),
										),
									),
						),
						),
			),
			'button_label' => 'Ajouter une section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'templates/sections.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
		4 => 'revisions',
		5 => 'slug',
		6 => 'author',
		7 => 'categories',
	),
	'active' => 1,
	'description' => '',
));

endif;
?>